FROM golang:1.22-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o gridmap cmd/gridmap/main.go

EXPOSE 8083

CMD ["./gridmap", "-config", "config/config.toml"]